version: "3"

services:
  kitchen-service:
    image: "nestjs-restaurant/kitchen-service"
    restart: always
    ports:
      - 3002:3000
    depends_on:
      - mongo_db_kitchen
    environment:
      - DINING_SERVICE_URL_WITH_PORT=${DINING_SERVICE}:3000
    networks:
      - nestjs-restaurant-network
  mongo_db_kitchen:
    image: "mongo:4.4.15"
    restart: always
    ports:
      - 27020:27017
    networks:
      - nestjs-restaurant-network
networks:
  nestjs-restaurant-network:
    driver: bridge
